### ISSUE TITLE
Feature idea: show WiFi and Bluetooth status

### ISSUE THREAD

**Issue by gbl08ma** [hidden-refuge/cpuvinf#2]
The RasPi 3 includes WiFi and Bluetooth radios, it could be interesting to display the status of these (as well as ethernet, why not). I'm not sure if there's an API for this that works across Linux distributions as personally I don't own a RasPi 3, but perhaps looking at ifconfig and iwconfig will suffice, at least for WiFi and Ethernet.

**Comment by ghost** [comment]
Now if I had a Raspberry Pi 3 I'd be working on that. I don't have one though and also currently don't have spare funds to buy one.

**Comment by ghost** [comment]
I do have a Raspberry Pi 3 now that I could use to implement this suggestion. Any help is welcome. I will see what I can do.

**Comment by gbl08ma** [comment]
Sadly I don't have one yet, I thought about buying one but given that my 2B sits unused... and I don't have any use in mind for a more powerful one... I thought I better save the money for something else.
Even my 1B+ will probably be decommissioned in a few weeks or months. It's currently responsible for some home automation stuff but we're moving to different solutions that don't require it.

I guess I can still test whether new CPUVinf versions still work on the B+ and 2B.
